### ISSUE TITLE
[Bug] 合并导入时没有检查文件中和程序内存中已有用户的用户名冲突

### ISSUE THREAD

**Issue by dixiatielu** [dixiatielu/library_book_manager#17]
应当检查文件中和程序内存中存储的已有用户的用户名冲突，由用户判断保留哪个。

**Comment by NostalgiaJohn** [comment]
补充：同时，应校验导入的图书信息和用户信息一致性

**Comment by dixiatielu** [comment]
https://github.com/dixiatielu/library_book_manager/commit/4411b1ace4cceeeee73d9932548181a243368a96
解决了检查用户名冲突的问题，但出现了新的问题：即导入后实际用户数量改变，但显示的用户数量不变，如图：
![image](https://github.com/dixiatielu/library_book_manager/assets/29675002/f29d757e-276d-4faf-93d4-63ba43241a3f)

**Comment by dixiatielu** [comment]
现在在发现重复ID时只会提示，下一步准备添加提示原来的用户信息和即将导入的信息
![image](https://github.com/dixiatielu/library_book_manager/assets/29675002/c2b004ed-5409-4708-9adc-0f68650e9b29)

**Comment by dixiatielu** [comment]
> 现在在发现重复ID时只会提示，下一步准备添加提示原来的用户信息和即将导入的信息 ![image](https://private-user-images.githubusercontent.com/29675002/296438730-c2b004ed-5409-4708-9adc-0f68650e9b29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMDkwMDMsIm5iZiI6MTcwNTIwODcwMywicGF0aCI6Ii8yOTY3NTAwMi8yOTY0Mzg3MzAtYzJiMDA0ZWQtNTQwOS00NzA4LTlhZGMtMGY2ODY1MGU5YjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDA1MDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNGJjYTRhYjU2MDRjN2YwNjQ0NjQ0OTNhN2FjMWFmOWM3YzIxYTdkMDgwODMwZmUzNDAyNDliMjhkZDNjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XbzB3BjCviPAjQRjl2cN6a3lZM-ogQGQ7YHXqjz2Aq0)


在 https://github.com/dixiatielu/library_book_manager/commit/fc5c7487e6538e3e3501f44ab048f7eaeea0ab82 里解决了上述问题，现在如果在添加用户时发现重复的就会提示原信息和新信息了。如图：
![image](https://github.com/dixiatielu/library_book_manager/assets/29675002/2439d31f-ca28-47e9-85fa-dccfe8c05db1)
